ah_dc            = "ams1"
ah_token         = "YOUREVERYLONGNEWTOKENANDTOPSECRET"
ah_machine_type  = "start-l"
ah_image_type    = "centos-7-x64"
ah_hdd           = "ssd2-ams1"
ah_fp            = "YOURESSHHASH"
private_key_path = "/root/.ssh/id_rsa.pub"
