---
- name: Clear gathered facts from all
  meta: clear_facts

- name: Disable IPv6 in grub
  replace:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="(.*)"'
    replace: 'GRUB_CMDLINE_LINUX="\1 ipv6.disable=1"'
    mode: '0644'
    backup: yes
  notify:
    - grub2-mkconfig
    - reboot_hosts