---
#- meta: end_play
#  when: (ansible_distribution != "CentOS" and ansible_distribution_major_version != "7")

#- name: Upgrade all packages
#  yum:
#        name: '*'
#        state: latest

- name: Remove postfix package
  yum:
        name: postfix
        state: absent

- yum:
    name:
      - epel-release
      - zip
      - unzip
      - bzip2
      - gzip
      - wget
      - libselinux-python
      - policycoreutils-python
      - git
      - curl
      - mc
      - vim
    state: present

- name: Change the hostname to our standard
  hostname:
      name: "{{ inventory_hostname }}"
  when:
      ansible_fqdn != ansible_host

- name: Build hosts file
  blockinfile:
      dest: /etc/cloud/templates/hosts.redhat.tmpl
      content: "{{ lookup('template', 'templates_etc_hosts.j2') }}"
      state: present